import { PricingSection } from "@/components/pricing";
import { Header } from "@/components/header";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-white dark:bg-zinc-950">
      <Header />

      {/* Hero */}
      <main className="flex-1 flex flex-col items-center justify-center px-6 py-24 text-center">
        <div className="inline-flex items-center rounded-full border border-zinc-200 dark:border-zinc-700 px-4 py-1.5 text-sm text-zinc-600 dark:text-zinc-400 mb-8">
          Free for 1 repo &middot; No credit card required
        </div>
        <h1 className="text-5xl font-bold tracking-tight text-zinc-900 dark:text-white max-w-3xl leading-tight">
          Your docs, always up to date.
          <br />
          <span className="text-zinc-400">Automatically.</span>
        </h1>
        <p className="mt-6 text-lg text-zinc-600 dark:text-zinc-400 max-w-xl leading-relaxed">
          DocuPilot generates and updates your README, API documentation, and
          CHANGELOG every time you push. Install the GitHub App and never write
          docs manually again.
        </p>
        <div className="mt-10 flex gap-4">
          <a
            href="https://github.com/apps/pushdocs"
            className="rounded-full bg-zinc-900 px-8 py-3 text-base font-medium text-white hover:bg-zinc-700 dark:bg-white dark:text-zinc-900 dark:hover:bg-zinc-200 transition-colors"
          >
            Get Started Free
          </a>
          <a
            href="#how-it-works"
            className="rounded-full border border-zinc-300 dark:border-zinc-700 px-8 py-3 text-base font-medium text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-900 transition-colors"
          >
            How It Works
          </a>
        </div>

        {/* How it works */}
        <section id="how-it-works" className="mt-32 w-full max-w-4xl">
          <h2 className="text-3xl font-bold text-zinc-900 dark:text-white mb-16">
            Three steps. Zero config.
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
            {[
              {
                step: "1",
                title: "Install",
                desc: "Add the DocuPilot GitHub App to your repositories.",
              },
              {
                step: "2",
                title: "Push",
                desc: "Push code as you normally do. DocuPilot watches for changes.",
              },
              {
                step: "3",
                title: "Done",
                desc: "README, CHANGELOG, and API docs are updated via pull request.",
              },
            ].map((item) => (
              <div key={item.step} className="text-left">
                <div className="text-4xl font-bold text-zinc-200 dark:text-zinc-700 mb-3">
                  {item.step}
                </div>
                <h3 className="text-xl font-semibold text-zinc-900 dark:text-white mb-2">
                  {item.title}
                </h3>
                <p className="text-zinc-600 dark:text-zinc-400">{item.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* See it in action */}
        <section className="mt-32 w-full max-w-4xl">
          <h2 className="text-3xl font-bold text-zinc-900 dark:text-white mb-6">
            See it in action
          </h2>
          <p className="text-zinc-600 dark:text-zinc-400 mb-8">
            Here&apos;s a real pull request generated by DocuPilot — README and
            CHANGELOG created automatically from a code push.
          </p>
          <a
            href="https://github.com/AkrMcmr/docupilot-test/pull/3"
            target="_blank"
            rel="noopener noreferrer"
            className="group block rounded-2xl border border-zinc-200 dark:border-zinc-700 p-6 hover:border-zinc-400 dark:hover:border-zinc-500 transition-colors text-left"
          >
            <div className="flex items-center gap-3 mb-4">
              <svg
                className="w-6 h-6 text-zinc-400"
                fill="currentColor"
                viewBox="0 0 16 16"
              >
                <path d="M7.177 3.073L9.573.677A.25.25 0 0110 .854v4.792a.25.25 0 01-.427.177L7.177 3.427a.25.25 0 010-.354zM3.75 2.5a.75.75 0 100 1.5.75.75 0 000-1.5zm-2.25.75a2.25 2.25 0 113 2.122v5.256a2.251 2.251 0 11-1.5 0V5.372A2.25 2.25 0 011.5 3.25zM11 2.5h-1V4h1a1 1 0 011 1v5.628a2.251 2.251 0 101.5 0V5A2.5 2.5 0 0011 2.5zm1 10.25a.75.75 0 111.5 0 .75.75 0 01-1.5 0zM3.75 12a.75.75 0 100 1.5.75.75 0 000-1.5z" />
              </svg>
              <span className="font-semibold text-zinc-900 dark:text-white">
                DocuPilot: Update documentation
              </span>
              <span className="text-xs rounded-full bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300 px-2 py-0.5">
                Open
              </span>
            </div>
            <div className="flex gap-6 text-sm text-zinc-500 dark:text-zinc-400">
              <span className="text-green-600 dark:text-green-400">
                +147 lines
              </span>
              <span>README.md</span>
              <span>CHANGELOG.md</span>
            </div>
            <p className="mt-3 text-sm text-zinc-500 dark:text-zinc-400 group-hover:text-zinc-700 dark:group-hover:text-zinc-300 transition-colors">
              View the full pull request on GitHub &rarr;
            </p>
          </a>
        </section>

        {/* Pricing */}
        <PricingSection />
      </main>

      {/* Footer */}
      <footer className="border-t border-zinc-200 dark:border-zinc-800 px-6 py-8 text-sm text-zinc-500">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <span>&copy; 2026 DocuPilot. Built for developers who ship.</span>
          <div className="flex items-center gap-6">
            <a
              href="https://github.com/AkrMcmr/docupilot"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-zinc-900 dark:hover:text-white transition-colors"
            >
              GitHub
            </a>
            <a
              href="https://github.com/AkrMcmr/docupilot/discussions"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-zinc-900 dark:hover:text-white transition-colors"
            >
              Community
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
